import { type NextPage } from "next";
import Head from "next/head";
import { HelpWidget } from "../components/HelpWidget";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat Widget</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-blue-400">
        <div className="items-left container flex flex-col justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Chat Widget
          </h1>
          <HelpWidget />
        </div>
      </main>
    </>
  );
};

export default Home;
